### ISSUE TITLE
Cannot pull new Docker image

### ISSUE THREAD

**Issue by gsantovena** [fastly/fastly-exporter#100]
Hello,

I'm receiving this message when trying to pull from the new place:

```
$ docker pull ghcr.io/fastly/fastly-exporter:latest
Error response from daemon: Head "https://ghcr.io/v2/fastly/fastly-exporter/manifests/latest": unauthorized
```

Thank you.

**Comment by shawnps** [comment]
@gsantovena sorry about that -- we recently migrated this repo to the fastly org which may have affected the Docker image permissions.

cc @phamann @thommahoney

**Comment by phamann** [comment]
@gsantovena thanks for reporting this. We've now fixed the package/iamge permisssions and thus it should now be public and able to pull.

Please can you test and confirm?

**Comment by gsantovena** [comment]
Thank you very much. Working now.
