### ISSUE TITLE
carnality explosion with fastly_rt_datacenter_info

### ISSUE THREAD

**Issue by mrnetops** [fastly/fastly-exporter#145]
fastly_rt_datacenter_info looks to have an unintended cardinality explosion.

Instead of the expected ~100 pop time series, it's getting multiplied by service, so we're getting 10s of thousands of time series instead.  

i.e. 
fastly_rt_datacenter_info{datacenter="ACC", group="Africa", latitude="5.573", longitude="-0.203", name="Ghana", **service="XXX"** }

**Comment by leklund** [comment]
@mrnetops on which version are you seeing this bug?

**Comment by mrnetops** [comment]
:facepalm: that is apparently on me, I look to be running an older version (v7.2.4).  I am not seeing this behavior in v7.6.1.

**Comment by mrnetops** [comment]
:facepalm: that is apparently on me, I look to be running an older version (v7.2.4).  I am not seeing this behavior in v7.6.1.  Thanks for checking, and we can close this out!
