### ISSUE TITLE
`-metric-blocklist` doesn't work with `fastly_rt_datacenter_info`

### ISSUE THREAD

**Issue by davidepedranz** [fastly/fastly-exporter#155]
The `-metric-blocklist` can't filter out the metric `fastly_rt_datacenter_info`.

Here is how to reproduce the issue with the latest stable version:

```shell
docker run \
  --env FASTLY_API_TOKEN="<your token>" \
  --interactive \
  --publish="0.0.0.0:8080:8080" \
  --rm \
  --tty \
  ghcr.io/fastly/fastly-exporter:v7.6.1 \
  -metric-blocklist='^fastly_rt_datacenter_info$'
```

```shell
curl -s http://127.0.0.1:8080/metrics | grep fastly_rt_datacenter_info
```

As you can see, the `fastly_rt_datacenter_info` continues to be exported, even if explicitly filtered out.

---

PS: Kudos for maintaining this exporter. It is really handy! 🙏🏼

**Comment by davidepedranz** [comment]
The same behaviour is there also for `fastly_rt_service_info` and `fastly_rt_last_successful_response`

**Comment by leklund** [comment]
Ah, interesting. We definitely aren't checking the filter for the `fastly_rt_service_info` and `fastly_rt_last_successful_response` metrics: https://github.com/fastly/fastly-exporter/blob/main/pkg/prom/metrics.go#L28

The datacenter metrics are a little different (implemented with a customer collector) but it seems like we could disable the datacenter cache / collector if `fastly_rt_datacenter_info` was in the blocklist.

**Comment by davidepedranz** [comment]
That sounds like a perfect solution for me! Thanks for looking into it 🙏🏼 

It isn't a crazy issue: I am just dropping the metrics I don't need with Prometheus relabeling rules. But it is just extra work It would be nice to move to configuration flags in the exporter itself.
