### ISSUE TITLE
fastly_rt_service_info for group_left/group_right metadata

### ISSUE THREAD

**Issue by mrnetops** [fastly/fastly-exporter#16]
https://www.robustperception.io/exposing-the-software-version-to-prometheus
https://www.robustperception.io/how-to-have-labels-for-machine-roles

Technically, we could do all kinds of fun stuff like
* fastly_rt_service_info
* fastly_rt_datacenter_info
* fastly_rt_domain_info
* fastly_rt_customer_info

and stuff all sorts of other one off tidbits in without binding them to the individual metrics.

We could even do service_name that way

something like
```
fastly_rt_service_info{service_id="$SID", service_name="$NAME", customer_id="$CID"} 1
fastly_rt_datacenter_info{datacenter_code="$CODE", datacenter_name="$NAME", datacenter_group="$GROUP", datacenter_shield="$SHIELD"} 1
```

**Comment by peterbourgon** [comment]
No objection, modulo the implementation. I suspect this should be very minimal changes.

**Comment by peterbourgon** [comment]
So we now have service_info with labels service_id, service_name, and service_version. In theory we could labels there for anything [returned by /service](https://docs.fastly.com/api/config#service), but I want to be judicious. Is customer_id really valuable in this context? Are there other fields that have clear and obvious value?

For datacenter, domain, and customer, I think it's a little less clear. These are meta-properties of your configuration or even Fastly itself, and maybe not directly related to individual services. I'm open to adding additional stuff like that, but I'd like to understand the use cases that information would enable. Do you have any? :)

**Comment by peterbourgon** [comment]
#80 adds the datacenter_info metric and establishes a pattern for arbitrary metadata. This issue is a bit general, so I'm gonna go ahead and close it — please open new issues for any additional metadata you'd like to see.
