### ISSUE TITLE
Idle services also trigger net/http "Client.Timeout exceeded while awaiting headers"

### ISSUE THREAD

**Issue by mrnetops** [fastly/fastly-exporter#17]
I just noticed that one of my idle developer services is regularly reporting timeouts

```
level=error component=monitors service_id=xxxxxxxxxxxxxxxxxx service_name=tmol.com err="Get https://rt.fastly.com/v1/channel/xxxxxxxxxxxxxxxxxx/ts/1541720127: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
level=error component=monitors service_id=xxxxxxxxxxxxxxxxxx service_name=tmol.com err="Get https://rt.fastly.com/v1/channel/xxxxxxxxxxxxxxxxxx/ts/1541720219: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
level=error component=monitors service_id=xxxxxxxxxxxxxxxxxx service_name=tmol.com err="Get https://rt.fastly.com/v1/channel/xxxxxxxxxxxxxxxxxx/ts/1541720441: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
level=error component=monitors service_id=xxxxxxxxxxxxxxxxxx service_name=tmol.com err="Get https://rt.fastly.com/v1/channel/xxxxxxxxxxxxxxxxxx/ts/1541720828: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
level=error component=monitors service_id=xxxxxxxxxxxxxxxxxx service_name=tmol.com err="Get https://rt.fastly.com/v1/channel/xxxxxxxxxxxxxxxxxx/ts/1541721003: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
```

Looking at the corresponding Fastly dashboard, there is a note about `There is currently no new data. Graphs will resume when data is received.`

Should we update the error messaging `This may also be an idle service`, or is there a better way to differentiate no data vs timeout/connectivity problems?

**Comment by peterbourgon** [comment]
For reference, [here is the http.Client used to make these requests](https://github.com/peterbourgon/fastly-exporter/blob/2e922a7505dd474cd1e03c6fb2b91f42727536ac/main.go#L77).

**Comment by peterbourgon** [comment]
That's interesting, the `ts` is clearly getting updated. How can that happen if the request is canceled?

**Comment by peterbourgon** [comment]
On the rt.fastly.com side, pretty confident no request will block for more than ~30 seconds. Maybe there's something fucky re: waiting for headers?

**Comment by mrnetops** [comment]
I suspect there is a lazy write/lazy publish optimization in play at rt.fastly.com where data is not produced if requests to the underlying service are not made.  

i.e. no performance data if yer site is in fact not performing ;)

The question is just a) is there a better way to differentiate session timeout vs no data and b) do we just update the error messages if we can't tell the difference?

**Comment by peterbourgon** [comment]
You're right that if there is no traffic to a service, rt.fastly.com will not return (or produce) any data. But an HTTP request to rt.fastly.com will always return in approximately 30 seconds, even if there is no data, and yield a new ts value. Even if the code that serves rt.fastly.com breaks this contract, the actual Fastly service that sits in front of it enforces a ~35 second request termination window. So, if an http.Client with a 60s timeout is hitting that timeout, there is something weird happening, almost certainly on the client side. (I think catching that client-side timeout and treating it special is probably not the right approach.)
