### ISSUE TITLE
Support scraping multiple services

### ISSUE THREAD

**Issue by titosand** [fastly/fastly-exporter#2]
It looks like we can only specify a single Fastly service ID in the exporter right now.

Some shops have multiple services/service ID's set up, so it would be useful to be able to pass a comma-separated string or something and scrape multiple services.

**Comment by titosand** [comment]
Addressed in https://github.com/peterbourgon/fastly-exporter/pull/3/

**Comment by peterbourgon** [comment]
Refactored and pulled in #4, thank you!

**Comment by peterbourgon** [comment]
https://github.com/peterbourgon/fastly-exporter/releases/tag/v0.0.3
