### ISSUE TITLE
Feature request: export service/version information

### ISSUE THREAD

**Issue by wosc** [fastly/fastly-exporter#26]
One quite helpful bit of information is at which time new versions of services were activated. The graphs in the Fastly management UI display this; it would be cool if one could set this up e.g. as Grafana annotations.

AFAICT the information is _in principle_ available from the Fastly API https://docs.fastly.com/api/config#version.

**Comment by peterbourgon** [comment]
I'm not against it, but it's not obvious to me how this would be encoded in Prometheus metrics. If someone has a good suggestion there, I can certainly take a shot at an implementation.

**Comment by wosc** [comment]
I guess the "Grafana annotations" part will need some additional jury-rigging ;), for the time being I'm mostly concerned with getting the information out of the API in the first place. Luckily, the version is a plain integer, so what do you think about something like this:

```
fastly_service_version{service_id="ABCxyz",service_name="www.example.com"} 123.0
fastly_service_version{service_id="DEFtuv",service_name="img.example.com"} 42.0
```

**Comment by peterbourgon** [comment]
Generally it's a mistake to report data like that in the actual value, rather prefer to put everything in labels and allow the value to be constant 1.

**Comment by wosc** [comment]
Oh. What are the risks/downsides? I have not been using Prometheus for all that long, so I guess I haven't painted myself into that particular corner yet (since I don't see anything wrong with the approach ;).

But to be honest I'm not very particular about the format -- all I want is to be able to retrieve a set of "sevice x has version y" items, which should be easy either way. (And possibly query "which version does service x have".) Thanks!

**Comment by peterbourgon** [comment]
@wosc Are you able to easily build and test the version in the branch associated with #30? If yes, please give it a shot and make sure it meets your requirements. If no, let me know and I'll cut a release for you.

**Comment by wosc** [comment]
Thanks to your Dockerfile building was very easy! (I did have to manually clone `peterbourgon/usage` to `vendor/` first, probably because I know nothing about the golang build toolchain yet ;).

The resulting metrics look fine to me, they give me the currently active version, which is exactly what I wanted. Thank you so much for building it! :)
```
fastly_rt_service_info{service_id="...",service_name="[PROD] www.zeit.de",service_version="152"} 1
fastly_rt_service_info{service_id="...",service_name="[PROD] img.zeit.de",service_version="65"} 1
```
