### ISSUE TITLE
Default endpoint value

### ISSUE THREAD

**Issue by AmandaHassoun** [fastly/fastly-exporter#67]
I ran into an issue deploying this exporter on k8s where I hadn't set the `endpoint` argument, which ended up defaulting to `http://127.0.0.1:8080/metrics`. So Prometheus wasn't able to scrape it, the pod's metrics endpoint wasn't reachable from other pods even though they all had access... While my team and I were troubleshooting, we realized that according to the [Dockerfile](https://github.com/peterbourgon/fastly-exporter/commit/0832a7e2e3d8c675644925cbec14d2c8edef1e09#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R24), the entrypoint is in fact `http://0.0.0.0:8080/metrics`! So shouldn't the default value of this argument also be `http://0.0.0.0:8080/metrics`?

**Comment by peterbourgon** [comment]
No, it's important that the default doesn't bind to all available interfaces. The Dockerfile has also been extracted to a separate repo, I don't maintain it. 

Set `-endpoint`! 😄
