### ISSUE TITLE
Expose fastly rt api 'recorded' timestamp in prometheus metrics

### ISSUE THREAD

**Issue by colakong** [fastly/fastly-exporter#68]
The [fastly real-time api](https://developer.fastly.com/reference/api/metrics-stats/realtime/) includes a `recorded` field in the response, which is a timestamp of when a metric was generated. This is currently represented in the [APIResponse struct](https://github.com/peterbourgon/fastly-exporter/blob/main/pkg/gen/gen.go#L23).

Prometheus can be asked to [honour the metric timestamps](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config) seen when scraping a target.

And the prometheus golang client allows for the [creation of metrics with timestamps](https://pkg.go.dev/github.com/prometheus/client_golang/prometheus?utm_source=godoc#NewMetricWithTimestamp).

This issue is to update the fastly-exporter to use the `recorded` field as the metric timestamp when converting fastly metrics to prometheus ones. Doing this could help keep fastly metrics from being offset from other scrape targets.

**Comment by peterbourgon** [comment]
This is meaningful if the timestamp of a given metric is substantially different than the current time. But in the case of the Fastly real-time API, this should never be the case: there will naturally be some delay, but it will be on the order of a few seconds at most. So it's not obvious to me what this would accomplish. Are you experiencing a problem that this would solve?

**Comment by colakong** [comment]
We are looking at moving from another implementation of a fastly-exporter to this one, and noticed that metric timestamps could be skewed. I'll close the issue, and follow-up if we run into a problem that this would solve ^^.

**Comment by peterbourgon** [comment]
OK! I'm happy to help if there does turn out to be an issue.
