### ISSUE TITLE
Missing Docker images

### ISSUE THREAD

**Issue by SuperQ** [fastly/fastly-exporter#71]
It looks like `mrnetops/fastly-exporter` is missing the `v6.1.0` release on Docker Hub..

**Comment by SuperQ** [comment]
Would it be useful to add a CI pipeline to publish them automatically?

**Comment by peterbourgon** [comment]
Nah, I'm not interested in supporting Docker containers as release artifacts.

**Comment by peterbourgon** [comment]
Ah, there's a repo for those! Please 301 to https://github.com/mrnetops/fastly-exporter-docker 🙏

**Comment by peterbourgon** [comment]
I'm reconsidering — if an Action can publish automatically, it might be fine.

**Comment by SuperQ** [comment]
GitHub actions or CircleCI, whatever works. This is how all the Prometheus components are auto-published with every git release tag.

**Comment by mrnetops** [comment]
@peterbourgon 
1) docker images updated
2) there is an option to trigger docker builds automatically on github release, but as near as I have managed to figure out, the trigger action and the dockerfile needs to be in the main repository.  I know I was unable to get my repository to trigger automatic builds based on releases from this repository.

**Comment by peterbourgon** [comment]
Working on this in #75

**Comment by peterbourgon** [comment]
Done now, let me know if you have issues.
