### ISSUE TITLE
RT API meta-metric

### ISSUE THREAD

**Issue by SuperQ** [fastly/fastly-exporter#74]
It would be useful to have a meta-metric like `fastly_rt_up` that indicates if the exporter has a valid connection to the RT API for each service.

**Comment by peterbourgon** [comment]
I like it.

**Comment by peterbourgon** [comment]
There's not really a concept of a valid connection, per se... what about a "last successful ~scrape~ _poll_" Unix timestamp?

**Comment by SuperQ** [comment]
LGTM, Thanks!
