### ISSUE TITLE
Add partial docker tags 

### ISSUE THREAD

**Issue by mrnetops** [fastly/fastly-exporter#82]
```
name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/peterbourgon/fastly-exporter
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
```
for 7, 7.0, 7.0.0 tags once we move out of alpha/beta/etc

* https://github.com/marketplace/actions/docker-metadata-action#semver
* https://github.com/docker/metadata-action#typesemver

**Comment by peterbourgon** [comment]
I don't totally understand the request, here. Can you say a bit more, or maybe make a strawman PR?

**Comment by mrnetops** [comment]
Sure, so right now the tag options for your docker images is as follows
```
{"name":"peterbourgon/fastly-exporter","tags":["v7.0.0-alpha.1","v7.0.0-alpha.2","v7.0.0-beta.1","latest"]}
```

To make this clearer, let's consider the arbitrary version v7.1.2.

With these additions, in addition to the specific version tag, fastly-exporter docker releases would ALSO be tagged as follows

```
# Per type=semver,pattern={{version}}
7.1.2
# Per type=semver,pattern={{major}}.{{minor}}
7.1
# Per type=semver,pattern={{major}}
7
``` 
Which allows folks to also pull
* ghcr.io/peterbourgon/fastly-exporter:7 if they want the latest version of major release 7.x.x
* ghcr.io/peterbourgon/fastly-exporter:7.1 if they want the latest version of minor release 7.1.x
* ghcr.io/peterbourgon/fastly-exporter:7.1.2 if they want specific patch version 7.1.2

**Comment by peterbourgon** [comment]
Sounds good, but I don't understand what "these additions" means :) Is it a new stage in the Action?

**Comment by mrnetops** [comment]
aaah, gotcha!  essentially, this slots into https://github.com/peterbourgon/fastly-exporter/blob/main/.github/workflows/ci.yaml#L75,L78 where you're adding the `tags:` section after `images:`, in the `with:` block.

so just adding more bits to the pre-exiting `uses: docker/metadata-action@v3` step.
```
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/peterbourgon/fastly-exporter
```
to
```
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/peterbourgon/fastly-exporter
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
```

Let me know if you would like a pr for that
