### ISSUE TITLE
Continue starting up if fastly is down

### ISSUE THREAD

**Issue by grahamc** [fastly/fastly-exporter#87]
Right now if Fastly is down or a temporary network glitch is occurring during startup the exporter crashes:

```
fastly # [    7.238528] prometheus-fastly-exporter-start[935]: level=error component=api.fastly.com during="initial API calls" err="error executing API services request: Get \"https://api.fastly.com/service\": dial tcp: lookup api.fastly.com: Temporary failure in name resolution"
fastly # [    7.242486] systemd[1]: prometheus-fastly-exporter.service: Main process exited, code=exited, status=1/FAILURE
```

For me it would be preferable for the exporter to continue starting up but emit a metric saying Fastly seems to be down.

re https://github.com/NixOS/nixpkgs/pull/151427/files#diff-e669f3682eb07a05197060a93f278ff57f160465c8168906e12f1f2c472026d8R262-R273

**Comment by peterbourgon** [comment]
Yep, this would be better.
