### ISSUE TITLE
Exporter should set it's own custom user-agent

### ISSUE THREAD

**Issue by phamann** [fastly/fastly-exporter#90]
It would be nice if the exporter can set a custom user-agent string so that it can be identified by downstream APIs. Such as `User-Agent: fastly-exporter v1.2.3`.

I'm happy to take this work on next week, but detailing here before I forget.

**Comment by peterbourgon** [comment]
We're already doing this [when querying rt.fastly.com](https://github.com/peterbourgon/fastly-exporter/blob/1e1277d4e643760037d8d6eea83afbb9e573b642/cmd/fastly-exporter/main.go#L289) so you can just do a similar thing for the API calls I guess.

**Comment by peterbourgon** [comment]
Could we bake the user agent into the client itself?

**Comment by peterbourgon** [comment]
@phamann @drhoden-fastly Take a look at `main` when you get a chance.

**Comment by phamann** [comment]
Woop, perfect! Thank you, @peterbourgon for all your help getting this issue across the line. 

Are we able to cut a new release with the recent changes from #92 and #88?

**Comment by peterbourgon** [comment]
https://github.com/peterbourgon/fastly-exporter/releases/v7.1.0 🖖
